
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.sap.xi.sd_sls;

import java.util.logging.Logger;
import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2018-11-21T10:15:02.387+05:30
 * Generated source version: 3.2.6
 *
 */

@javax.jws.WebService(
                      serviceName = "service",
                      portName = "binding",
                      targetNamespace = "http://sap.com/xi/SD-SLS",
                      wsdlLocation = "file:salesorder.wsdl",
                      endpointInterface = "com.sap.xi.sd_sls.SalesOrderBulkRequestIn")

public class BindingImpl implements SalesOrderBulkRequestIn {

    private static final Logger LOG = Logger.getLogger(BindingImpl.class.getName());

    /* (non-Javadoc)
     * @see com.sap.xi.sd_sls.SalesOrderBulkRequestIn#salesOrderBulkRequestIn(com.sap.xi.sd_sls.SalesOrderBulkMessage salesOrderBulkRequest)*
     */
    public void salesOrderBulkRequestIn(SalesOrderBulkMessage salesOrderBulkRequest) {
        LOG.info("Executing operation salesOrderBulkRequestIn");
        System.out.println(salesOrderBulkRequest);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
