/*
 * Reservation Document - Read, Create, Delete
 * This service enables you to retrieve,  create and delete reservation documents.  For example, a user might create a  reservation for a material with some  quantity and assign that reserved material  to a cost center, a sales order or an  asset. A reservation can also be created  for a transfer posting from one plant to  another. The service also allows to delete  existing reservation documents. It can be  consumed by external systems and user  interfaces.
 *
 * OpenAPI spec version: 1 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.sap.apibhub.sdk.api_reservation_document_srv.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * APIRESERVATIONDOCUMENTSRVAReservationDocumentItemType
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-08-07T11:14:01.327Z")
public class APIRESERVATIONDOCUMENTSRVAReservationDocumentItemType {
  @SerializedName("Reservation")
  private String reservation = null;

  @SerializedName("ReservationItem")
  private String reservationItem = null;

  @SerializedName("RecordType")
  private String recordType = null;
  
  @SerializedName("Product")
  private String product = null;
  
  @SerializedName("RequirementType")
  private String requirementType = null;
  
  @SerializedName("MatlCompRequirementDate")
  private String matlCompRequirementDate = null;
  
  @SerializedName("Plant")
  private String plant = null;
  
  @SerializedName("ManufacturingOrderOperation")
  private String manufacturingOrderOperation = null;
  
  @SerializedName("GoodsMovementIsAllowed")
  private String goodsMovementIsAllowed = null;
  
  @SerializedName("StorageLocation")
  private String storageLocation = null;
  
  @SerializedName("Batch")
  private String batch = null;
  
  @SerializedName("DebitCreditCode")
  private String debitCreditCode = null;
  
  @SerializedName("BaseUnit")
  private String baseUnit = null;
  
  @SerializedName("GLAccount")
  private String gLAccount = null;
  
  @SerializedName("GoodsMovementType")
  private String goodsMovementType = null;
  
  @SerializedName("EntryUnit")
  private String entryUnit = null;
  
  @SerializedName("QuantityIsFixed")
  private String quantityIsFixed = null;
  
  @SerializedName("CompanyCodeCurrency")
  private String companyCodeCurrency = null;
  
  @SerializedName("IssuingOrReceivingPlant")
  private String issuingOrReceivingPlant = null;
  
  @SerializedName("IssuingOrReceivingStorageLoc")
  private String issuingOrReceivingStorageLoc = null;
  
  @SerializedName("PurchasingDocument")
  private String purchasingDocument = null;
  
  @SerializedName("PurchasingDocumentItem")
  private String purchasingDocumentItem = null;
  
  @SerializedName("Supplier")
  private String supplier = null;
  
  @SerializedName("ResvnItmRequiredQtyInBaseUnit")
  private String resvnItmRequiredQtyInBaseUnit = null;
  
  @SerializedName("ReservationItemIsFinallyIssued")
  private String reservationItemIsFinallyIssued = null;
  
  @SerializedName("ReservationItmIsMarkedForDeltn")
  private String reservationItmIsMarkedForDeltn = null;
  
  @SerializedName("ResvnItmRequiredQtyInEntryUnit")
  private String resvnItmRequiredQtyInEntryUnit = null;
  
  @SerializedName("ResvnItmWithdrawnQtyInBaseUnit")
  private String resvnItmWithdrawnQtyInBaseUnit = null;
  
  @SerializedName("ResvnItmWithdrawnAmtInCCCrcy")
  private String resvnItmWithdrawnAmtInCCCrcy = null;
  
  @SerializedName("GoodsRecipientName")
  private String goodsRecipientName = null;
  
  @SerializedName("UnloadingPointName")
  private String unloadingPointName = null;
  
  @SerializedName("ReservationItemText")
  private String reservationItemText = null;

  public APIRESERVATIONDOCUMENTSRVAReservationDocumentItemType reservation(String reservation) {
    this.reservation = reservation;
    return this;
  }

   /**
   * Number of Reservation/Dependent Requirement   Alphanumeric key uniquely identifying the document.
   * @return reservation
  **/
  @ApiModelProperty(value = "Number of Reservation/Dependent Requirement   Alphanumeric key uniquely identifying the document.")
  public String getReservation() {
    return reservation;
  }

  public void setReservation(String reservation) {
    this.reservation = reservation;
  }

  public APIRESERVATIONDOCUMENTSRVAReservationDocumentItemType reservationItem(String reservationItem) {
    this.reservationItem = reservationItem;
    return this;
  }

   /**
   * Item Number of Reservation/Dependent Requirement   Specifies the number that uniquely identifies an item in .
   * @return reservationItem
  **/
  @ApiModelProperty(value = "Item Number of Reservation/Dependent Requirement   Specifies the number that uniquely identifies an item in .")
  public String getReservationItem() {
    return reservationItem;
  }

  public void setReservationItem(String reservationItem) {
    this.reservationItem = reservationItem;
  }

  public APIRESERVATIONDOCUMENTSRVAReservationDocumentItemType recordType(String recordType) {
    this.recordType = recordType;
    return this;
  }

   /**
   * Get recordType
   * @return recordType
  **/
  @ApiModelProperty(value = "")
  public String getRecordType() {
    return recordType;
  }

  public void setRecordType(String recordType) {
    this.recordType = recordType;
  }
  
  
  


  public String getProduct() {
	return product;
}

public void setProduct(String product) {
	this.product = product;
}

public String getRequirementType() {
	return requirementType;
}

public void setRequirementType(String requirementType) {
	this.requirementType = requirementType;
}

public String getMatlCompRequirementDate() {
	return matlCompRequirementDate;
}

public void setMatlCompRequirementDate(String matlCompRequirementDate) {
	this.matlCompRequirementDate = matlCompRequirementDate;
}

public String getPlant() {
	return plant;
}

public void setPlant(String plant) {
	this.plant = plant;
}

public String getManufacturingOrderOperation() {
	return manufacturingOrderOperation;
}

public void setManufacturingOrderOperation(String manufacturingOrderOperation) {
	this.manufacturingOrderOperation = manufacturingOrderOperation;
}

public String getGoodsMovementIsAllowed() {
	return goodsMovementIsAllowed;
}

public void setGoodsMovementIsAllowed(String goodsMovementIsAllowed) {
	this.goodsMovementIsAllowed = goodsMovementIsAllowed;
}

public String getStorageLocation() {
	return storageLocation;
}

public void setStorageLocation(String storageLocation) {
	this.storageLocation = storageLocation;
}

public String getBatch() {
	return batch;
}

public void setBatch(String batch) {
	this.batch = batch;
}

public String getDebitCreditCode() {
	return debitCreditCode;
}

public void setDebitCreditCode(String debitCreditCode) {
	this.debitCreditCode = debitCreditCode;
}

public String getBaseUnit() {
	return baseUnit;
}

public void setBaseUnit(String baseUnit) {
	this.baseUnit = baseUnit;
}

public String getgLAccount() {
	return gLAccount;
}

public void setgLAccount(String gLAccount) {
	this.gLAccount = gLAccount;
}

public String getGoodsMovementType() {
	return goodsMovementType;
}

public void setGoodsMovementType(String goodsMovementType) {
	this.goodsMovementType = goodsMovementType;
}

public String getEntryUnit() {
	return entryUnit;
}

public void setEntryUnit(String entryUnit) {
	this.entryUnit = entryUnit;
}

public String getQuantityIsFixed() {
	return quantityIsFixed;
}

public void setQuantityIsFixed(String quantityIsFixed) {
	this.quantityIsFixed = quantityIsFixed;
}

public String getCompanyCodeCurrency() {
	return companyCodeCurrency;
}

public void setCompanyCodeCurrency(String companyCodeCurrency) {
	this.companyCodeCurrency = companyCodeCurrency;
}

public String getIssuingOrReceivingPlant() {
	return issuingOrReceivingPlant;
}

public void setIssuingOrReceivingPlant(String issuingOrReceivingPlant) {
	this.issuingOrReceivingPlant = issuingOrReceivingPlant;
}

public String getIssuingOrReceivingStorageLoc() {
	return issuingOrReceivingStorageLoc;
}

public void setIssuingOrReceivingStorageLoc(String issuingOrReceivingStorageLoc) {
	this.issuingOrReceivingStorageLoc = issuingOrReceivingStorageLoc;
}

public String getPurchasingDocument() {
	return purchasingDocument;
}

public void setPurchasingDocument(String purchasingDocument) {
	this.purchasingDocument = purchasingDocument;
}

public String getPurchasingDocumentItem() {
	return purchasingDocumentItem;
}

public void setPurchasingDocumentItem(String purchasingDocumentItem) {
	this.purchasingDocumentItem = purchasingDocumentItem;
}

public String getSupplier() {
	return supplier;
}

public void setSupplier(String supplier) {
	this.supplier = supplier;
}

public String getResvnItmRequiredQtyInBaseUnit() {
	return resvnItmRequiredQtyInBaseUnit;
}

public void setResvnItmRequiredQtyInBaseUnit(String resvnItmRequiredQtyInBaseUnit) {
	this.resvnItmRequiredQtyInBaseUnit = resvnItmRequiredQtyInBaseUnit;
}

public String getReservationItemIsFinallyIssued() {
	return reservationItemIsFinallyIssued;
}

public void setReservationItemIsFinallyIssued(String reservationItemIsFinallyIssued) {
	this.reservationItemIsFinallyIssued = reservationItemIsFinallyIssued;
}

public String getReservationItmIsMarkedForDeltn() {
	return reservationItmIsMarkedForDeltn;
}

public void setReservationItmIsMarkedForDeltn(String reservationItmIsMarkedForDeltn) {
	this.reservationItmIsMarkedForDeltn = reservationItmIsMarkedForDeltn;
}

public String getResvnItmRequiredQtyInEntryUnit() {
	return resvnItmRequiredQtyInEntryUnit;
}

public void setResvnItmRequiredQtyInEntryUnit(String resvnItmRequiredQtyInEntryUnit) {
	this.resvnItmRequiredQtyInEntryUnit = resvnItmRequiredQtyInEntryUnit;
}

public String getResvnItmWithdrawnQtyInBaseUnit() {
	return resvnItmWithdrawnQtyInBaseUnit;
}

public void setResvnItmWithdrawnQtyInBaseUnit(String resvnItmWithdrawnQtyInBaseUnit) {
	this.resvnItmWithdrawnQtyInBaseUnit = resvnItmWithdrawnQtyInBaseUnit;
}

public String getResvnItmWithdrawnAmtInCCCrcy() {
	return resvnItmWithdrawnAmtInCCCrcy;
}

public void setResvnItmWithdrawnAmtInCCCrcy(String resvnItmWithdrawnAmtInCCCrcy) {
	this.resvnItmWithdrawnAmtInCCCrcy = resvnItmWithdrawnAmtInCCCrcy;
}

public String getGoodsRecipientName() {
	return goodsRecipientName;
}

public void setGoodsRecipientName(String goodsRecipientName) {
	this.goodsRecipientName = goodsRecipientName;
}

public String getUnloadingPointName() {
	return unloadingPointName;
}

public void setUnloadingPointName(String unloadingPointName) {
	this.unloadingPointName = unloadingPointName;
}

public String getReservationItemText() {
	return reservationItemText;
}

public void setReservationItemText(String reservationItemText) {
	this.reservationItemText = reservationItemText;
}

@Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    APIRESERVATIONDOCUMENTSRVAReservationDocumentItemType apIRESERVATIONDOCUMENTSRVAReservationDocumentItemType = (APIRESERVATIONDOCUMENTSRVAReservationDocumentItemType) o;
    return Objects.equals(this.reservation, apIRESERVATIONDOCUMENTSRVAReservationDocumentItemType.reservation) &&
        Objects.equals(this.reservationItem, apIRESERVATIONDOCUMENTSRVAReservationDocumentItemType.reservationItem) &&
        Objects.equals(this.recordType, apIRESERVATIONDOCUMENTSRVAReservationDocumentItemType.recordType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(reservation, reservationItem, recordType);
  }


  
  
  
  

    @Override
	public String toString() {
		return "APIRESERVATIONDOCUMENTSRVAReservationDocumentItemType [reservation=" + reservation + ", reservationItem="
				+ reservationItem + ",\n recordType=" + recordType + ", product=" + product + ", requirementType="
				+ requirementType + ",\n matlCompRequirementDate=" + matlCompRequirementDate + ", plant=" + plant
				+ ",\n manufacturingOrderOperation=" + manufacturingOrderOperation + ", goodsMovementIsAllowed="
				+ goodsMovementIsAllowed + ",\n storageLocation=" + storageLocation + ", batch=" + batch
				+ ",\n debitCreditCode=" + debitCreditCode + ", baseUnit=" + baseUnit + ", gLAccount=" + gLAccount
				+ ",\n goodsMovementType=" + goodsMovementType + ", entryUnit=" + entryUnit + ", quantityIsFixed="
				+ quantityIsFixed + ",\n companyCodeCurrency=" + companyCodeCurrency + ", issuingOrReceivingPlant="
				+ issuingOrReceivingPlant + ",\n issuingOrReceivingStorageLoc=" + issuingOrReceivingStorageLoc
				+ ",\n purchasingDocument=" + purchasingDocument + ", purchasingDocumentItem=" + purchasingDocumentItem
				+ ",\n supplier=" + supplier + ", resvnItmRequiredQtyInBaseUnit=" + resvnItmRequiredQtyInBaseUnit
				+ ",\n reservationItemIsFinallyIssued=" + reservationItemIsFinallyIssued + ", reservationItmIsMarkedForDeltn="
				+ reservationItmIsMarkedForDeltn + ",\n resvnItmRequiredQtyInEntryUnit=" + resvnItmRequiredQtyInEntryUnit
				+ ",\n resvnItmWithdrawnQtyInBaseUnit=" + resvnItmWithdrawnQtyInBaseUnit + ", resvnItmWithdrawnAmtInCCCrcy="
				+ resvnItmWithdrawnAmtInCCCrcy + ",\n goodsRecipientName=" + goodsRecipientName + ", unloadingPointName="
				+ unloadingPointName + ",\n reservationItemText=" + reservationItemText + "]";
	}
    
  
/**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

