/*
 * Reservation Document - Read, Create, Delete
 * This service enables you to retrieve,  create and delete reservation documents.  For example, a user might create a  reservation for a material with some  quantity and assign that reserved material  to a cost center, a sales order or an  asset. A reservation can also be created  for a transfer posting from one plant to  another. The service also allows to delete  existing reservation documents. It can be  consumed by external systems and user  interfaces.
 *
 * OpenAPI spec version: 1 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.sap.apibhub.sdk.api_reservation_document_srv.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * APIRESERVATIONDOCUMENTSRVAReservationDocumentItemTypeCreate
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-08-07T11:14:01.327Z")
public class APIRESERVATIONDOCUMENTSRVAReservationDocumentItemTypeCreate {
  @SerializedName("Reservation")
  private String reservation = null;

  @SerializedName("ReservationItem")
  private String reservationItem = null;

  @SerializedName("RecordType")
  private String recordType = null;

  public APIRESERVATIONDOCUMENTSRVAReservationDocumentItemTypeCreate reservation(String reservation) {
    this.reservation = reservation;
    return this;
  }

   /**
   * Number of Reservation/Dependent Requirement   Alphanumeric key uniquely identifying the document.
   * @return reservation
  **/
  @ApiModelProperty(required = true, value = "Number of Reservation/Dependent Requirement   Alphanumeric key uniquely identifying the document.")
  public String getReservation() {
    return reservation;
  }

  public void setReservation(String reservation) {
    this.reservation = reservation;
  }

  public APIRESERVATIONDOCUMENTSRVAReservationDocumentItemTypeCreate reservationItem(String reservationItem) {
    this.reservationItem = reservationItem;
    return this;
  }

   /**
   * Item Number of Reservation/Dependent Requirement   Specifies the number that uniquely identifies an item in .
   * @return reservationItem
  **/
  @ApiModelProperty(required = true, value = "Item Number of Reservation/Dependent Requirement   Specifies the number that uniquely identifies an item in .")
  public String getReservationItem() {
    return reservationItem;
  }

  public void setReservationItem(String reservationItem) {
    this.reservationItem = reservationItem;
  }

  public APIRESERVATIONDOCUMENTSRVAReservationDocumentItemTypeCreate recordType(String recordType) {
    this.recordType = recordType;
    return this;
  }

   /**
   * Get recordType
   * @return recordType
  **/
  @ApiModelProperty(required = true, value = "")
  public String getRecordType() {
    return recordType;
  }

  public void setRecordType(String recordType) {
    this.recordType = recordType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    APIRESERVATIONDOCUMENTSRVAReservationDocumentItemTypeCreate apIRESERVATIONDOCUMENTSRVAReservationDocumentItemTypeCreate = (APIRESERVATIONDOCUMENTSRVAReservationDocumentItemTypeCreate) o;
    return Objects.equals(this.reservation, apIRESERVATIONDOCUMENTSRVAReservationDocumentItemTypeCreate.reservation) &&
        Objects.equals(this.reservationItem, apIRESERVATIONDOCUMENTSRVAReservationDocumentItemTypeCreate.reservationItem) &&
        Objects.equals(this.recordType, apIRESERVATIONDOCUMENTSRVAReservationDocumentItemTypeCreate.recordType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(reservation, reservationItem, recordType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class APIRESERVATIONDOCUMENTSRVAReservationDocumentItemTypeCreate {\n");
    
    sb.append("    reservation: ").append(toIndentedString(reservation)).append("\n");
    sb.append("    reservationItem: ").append(toIndentedString(reservationItem)).append("\n");
    sb.append("    recordType: ").append(toIndentedString(recordType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

