/*
 * Sales Order - Create, Read, Update, Delete (A2X)
 * You can use this service to integrate external  applications with sales order processing in SAP  S/4HANA Cloud. In every API call, you can make  use of the following operations:  - You can retrieve  sales orders. Apply any of the filters provided or  retrieve all existing data.  - You can create sales  orders. Note that you must use “deep insert”  requests (a header plus the following entities:  header partner, header pricing element, header  text, payment details, item, item partner, item  pricing element, and item text). You cannot create  entities without including any related entities.  - For  existing sales orders, you can create new items.  Note that you must use “deep insert” requests  (with the following entities: item partner, item pricing  element, and item text). You cannot create entities  without including any related entities.  - For existing  sales orders, you can update the header, header  partner, header pricing element, header text,  payment details, item, item partner, item pricing  element, and item text.  - For existing sales  orders, you can delete the header, header partner,  header pricing element, header text, payment  details, item, item partner, item pricing element,  and item text.  - You can accept or deny approval  requests for sales orders that cannot be processed  without the consent of an approver.
 *
 * OpenAPI spec version: 1 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.sap.apibhub.sdk.api_sales_order_srv.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.sap.apibhub.sdk.api_sales_order_srv.model.APISALESORDERSRVASalesOrderType;
import com.sap.apibhub.sdk.api_sales_order_srv.model.CollectionOfASalesOrderItemPartnerType;
import com.sap.apibhub.sdk.api_sales_order_srv.model.CollectionOfASalesOrderItemPrElementType;
import com.sap.apibhub.sdk.api_sales_order_srv.model.CollectionOfASalesOrderItemTextType;
import com.sap.apibhub.sdk.api_sales_order_srv.model.CollectionOfASalesOrderScheduleLineType;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Sales Order Item (API)
 */
@ApiModel(description = "Sales Order Item (API)")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-08-07T13:59:02.462Z")
public class APISALESORDERSRVASalesOrderItemType {
  @SerializedName("SalesOrder")
  private String salesOrder = null;

  @SerializedName("SalesOrderItem")
  private String salesOrderItem = null;

  @SerializedName("to_Partner")
  private CollectionOfASalesOrderItemPartnerType toPartner = null;

  @SerializedName("to_PricingElement")
  private CollectionOfASalesOrderItemPrElementType toPricingElement = null;

  @SerializedName("to_SalesOrder")
  private APISALESORDERSRVASalesOrderType toSalesOrder = null;

  @SerializedName("to_ScheduleLine")
  private CollectionOfASalesOrderScheduleLineType toScheduleLine = null;

  @SerializedName("to_Text")
  private CollectionOfASalesOrderItemTextType toText = null;

  public APISALESORDERSRVASalesOrderItemType salesOrder(String salesOrder) {
    this.salesOrder = salesOrder;
    return this;
  }

   /**
   * Sales Order
   * @return salesOrder
  **/
  @ApiModelProperty(value = "Sales Order")
  public String getSalesOrder() {
    return salesOrder;
  }

  public void setSalesOrder(String salesOrder) {
    this.salesOrder = salesOrder;
  }

  public APISALESORDERSRVASalesOrderItemType salesOrderItem(String salesOrderItem) {
    this.salesOrderItem = salesOrderItem;
    return this;
  }

   /**
   * Sales Order Item
   * @return salesOrderItem
  **/
  @ApiModelProperty(value = "Sales Order Item")
  public String getSalesOrderItem() {
    return salesOrderItem;
  }

  public void setSalesOrderItem(String salesOrderItem) {
    this.salesOrderItem = salesOrderItem;
  }

  public APISALESORDERSRVASalesOrderItemType toPartner(CollectionOfASalesOrderItemPartnerType toPartner) {
    this.toPartner = toPartner;
    return this;
  }

   /**
   * Get toPartner
   * @return toPartner
  **/
  @ApiModelProperty(value = "")
  public CollectionOfASalesOrderItemPartnerType getToPartner() {
    return toPartner;
  }

  public void setToPartner(CollectionOfASalesOrderItemPartnerType toPartner) {
    this.toPartner = toPartner;
  }

  public APISALESORDERSRVASalesOrderItemType toPricingElement(CollectionOfASalesOrderItemPrElementType toPricingElement) {
    this.toPricingElement = toPricingElement;
    return this;
  }

   /**
   * Get toPricingElement
   * @return toPricingElement
  **/
  @ApiModelProperty(value = "")
  public CollectionOfASalesOrderItemPrElementType getToPricingElement() {
    return toPricingElement;
  }

  public void setToPricingElement(CollectionOfASalesOrderItemPrElementType toPricingElement) {
    this.toPricingElement = toPricingElement;
  }

  public APISALESORDERSRVASalesOrderItemType toSalesOrder(APISALESORDERSRVASalesOrderType toSalesOrder) {
    this.toSalesOrder = toSalesOrder;
    return this;
  }

   /**
   * Get toSalesOrder
   * @return toSalesOrder
  **/
  @ApiModelProperty(value = "")
  public APISALESORDERSRVASalesOrderType getToSalesOrder() {
    return toSalesOrder;
  }

  public void setToSalesOrder(APISALESORDERSRVASalesOrderType toSalesOrder) {
    this.toSalesOrder = toSalesOrder;
  }

  public APISALESORDERSRVASalesOrderItemType toScheduleLine(CollectionOfASalesOrderScheduleLineType toScheduleLine) {
    this.toScheduleLine = toScheduleLine;
    return this;
  }

   /**
   * Get toScheduleLine
   * @return toScheduleLine
  **/
  @ApiModelProperty(value = "")
  public CollectionOfASalesOrderScheduleLineType getToScheduleLine() {
    return toScheduleLine;
  }

  public void setToScheduleLine(CollectionOfASalesOrderScheduleLineType toScheduleLine) {
    this.toScheduleLine = toScheduleLine;
  }

  public APISALESORDERSRVASalesOrderItemType toText(CollectionOfASalesOrderItemTextType toText) {
    this.toText = toText;
    return this;
  }

   /**
   * Get toText
   * @return toText
  **/
  @ApiModelProperty(value = "")
  public CollectionOfASalesOrderItemTextType getToText() {
    return toText;
  }

  public void setToText(CollectionOfASalesOrderItemTextType toText) {
    this.toText = toText;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    APISALESORDERSRVASalesOrderItemType apISALESORDERSRVASalesOrderItemType = (APISALESORDERSRVASalesOrderItemType) o;
    return Objects.equals(this.salesOrder, apISALESORDERSRVASalesOrderItemType.salesOrder) &&
        Objects.equals(this.salesOrderItem, apISALESORDERSRVASalesOrderItemType.salesOrderItem) &&
        Objects.equals(this.toPartner, apISALESORDERSRVASalesOrderItemType.toPartner) &&
        Objects.equals(this.toPricingElement, apISALESORDERSRVASalesOrderItemType.toPricingElement) &&
        Objects.equals(this.toSalesOrder, apISALESORDERSRVASalesOrderItemType.toSalesOrder) &&
        Objects.equals(this.toScheduleLine, apISALESORDERSRVASalesOrderItemType.toScheduleLine) &&
        Objects.equals(this.toText, apISALESORDERSRVASalesOrderItemType.toText);
  }

  @Override
  public int hashCode() {
    return Objects.hash(salesOrder, salesOrderItem, toPartner, toPricingElement, toSalesOrder, toScheduleLine, toText);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class APISALESORDERSRVASalesOrderItemType {\n");
    
    sb.append("    salesOrder: ").append(toIndentedString(salesOrder)).append("\n");
    sb.append("    salesOrderItem: ").append(toIndentedString(salesOrderItem)).append("\n");
    sb.append("    toPartner: ").append(toIndentedString(toPartner)).append("\n");
    sb.append("    toPricingElement: ").append(toIndentedString(toPricingElement)).append("\n");
    sb.append("    toSalesOrder: ").append(toIndentedString(toSalesOrder)).append("\n");
    sb.append("    toScheduleLine: ").append(toIndentedString(toScheduleLine)).append("\n");
    sb.append("    toText: ").append(toIndentedString(toText)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

