/*
 * Material Stock Display
 * This service enables you to retrieve material stock information using the OData protocol with filter data provided in the payload. It can be consumed by external warehouse applications.
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.sap.apibhub.sdk.api_material_stock_srv.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.sap.apibhub.sdk.api_material_stock_srv.model.CollectionOfAMatlStkInAcctModType;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * API view by consuming Material Stock
 */
@ApiModel(description = "API view by consuming Material Stock")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-08-07T13:00:53.757Z")
public class APIMATERIALSTOCKSRVAMaterialStockType {
  @SerializedName("Material")
  private String material = null;

  @SerializedName("to_MatlStkInAcctMod")
  private CollectionOfAMatlStkInAcctModType toMatlStkInAcctMod = null;

  public APIMATERIALSTOCKSRVAMaterialStockType material(String material) {
    this.material = material;
    return this;
  }

   /**
   * Material Number
   * @return material
  **/
  @ApiModelProperty(value = "Material Number")
  public String getMaterial() {
    return material;
  }

  public void setMaterial(String material) {
    this.material = material;
  }

  public APIMATERIALSTOCKSRVAMaterialStockType toMatlStkInAcctMod(CollectionOfAMatlStkInAcctModType toMatlStkInAcctMod) {
    this.toMatlStkInAcctMod = toMatlStkInAcctMod;
    return this;
  }

   /**
   * Get toMatlStkInAcctMod
   * @return toMatlStkInAcctMod
  **/
  @ApiModelProperty(value = "")
  public CollectionOfAMatlStkInAcctModType getToMatlStkInAcctMod() {
    return toMatlStkInAcctMod;
  }

  public void setToMatlStkInAcctMod(CollectionOfAMatlStkInAcctModType toMatlStkInAcctMod) {
    this.toMatlStkInAcctMod = toMatlStkInAcctMod;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    APIMATERIALSTOCKSRVAMaterialStockType apIMATERIALSTOCKSRVAMaterialStockType = (APIMATERIALSTOCKSRVAMaterialStockType) o;
    return Objects.equals(this.material, apIMATERIALSTOCKSRVAMaterialStockType.material) &&
        Objects.equals(this.toMatlStkInAcctMod, apIMATERIALSTOCKSRVAMaterialStockType.toMatlStkInAcctMod);
  }

  @Override
  public int hashCode() {
    return Objects.hash(material, toMatlStkInAcctMod);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class APIMATERIALSTOCKSRVAMaterialStockType {\n");
    
    sb.append("    material: ").append(toIndentedString(material)).append("\n");
    sb.append("    toMatlStkInAcctMod: ").append(toIndentedString(toMatlStkInAcctMod)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

