/*
 * Material Stock Display
 * This service enables you to retrieve material stock information using the OData protocol with filter data provided in the payload. It can be consumed by external warehouse applications.
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.sap.apibhub.sdk.api_material_stock_srv.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.sap.apibhub.sdk.api_material_stock_srv.model.APIMATERIALSTOCKSRVAMaterialStockType;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * API view by directly consuming I_MaterialStock
 */
@ApiModel(description = "API view by directly consuming I_MaterialStock")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-08-07T13:00:53.757Z")
public class APIMATERIALSTOCKSRVAMatlStkInAcctModType {
  @SerializedName("Material")
  private String material = null;

  @SerializedName("InventorySpecialStockType")
  private String inventorySpecialStockType = null;

  @SerializedName("InventoryStockType")
  private String inventoryStockType = null;

  @SerializedName("Plant")
  private String plant = null;

  @SerializedName("StorageLocation")
  private String storageLocation = null;

  @SerializedName("Batch")
  private String batch = null;

  @SerializedName("Supplier")
  private String supplier = null;

  @SerializedName("Customer")
  private String customer = null;

  @SerializedName("WBSElementInternalID")
  private String wbSElementInternalID = null;

  @SerializedName("SDDocument")
  private String sdDocument = null;

  @SerializedName("SDDocumentItem")
  private String sdDocumentItem = null;
  
  @SerializedName("MatlWrhsStkQtyInMatlBaseUnit")
  private String matlWrhsStkQtyInMatlBaseUnit = null;
  
  @SerializedName("MaterialBaseUnit")
  private String materialBaseUnit = null;

  @SerializedName("to_MaterialStock")
  private APIMATERIALSTOCKSRVAMaterialStockType toMaterialStock = null;

  public APIMATERIALSTOCKSRVAMatlStkInAcctModType material(String material) {
    this.material = material;
    return this;
  }

   /**
   * Material in Respect of Which Stock is Managed
   * @return material
  **/
  @ApiModelProperty(value = "Material in Respect of Which Stock is Managed")
  public String getMaterial() {
    return material;
  }

  public void setMaterial(String material) {
    this.material = material;
  }

  public APIMATERIALSTOCKSRVAMatlStkInAcctModType inventorySpecialStockType(String inventorySpecialStockType) {
    this.inventorySpecialStockType = inventorySpecialStockType;
    return this;
  }

   /**
   * Special Stock Indicator
   * @return inventorySpecialStockType
  **/
  @ApiModelProperty(value = "Special Stock Indicator")
  public String getInventorySpecialStockType() {
    return inventorySpecialStockType;
  }

  public void setInventorySpecialStockType(String inventorySpecialStockType) {
    this.inventorySpecialStockType = inventorySpecialStockType;
  }

  public APIMATERIALSTOCKSRVAMatlStkInAcctModType inventoryStockType(String inventoryStockType) {
    this.inventoryStockType = inventoryStockType;
    return this;
  }

   /**
   * Stock Type of Goods Movement (Stock Identifier)
   * @return inventoryStockType
  **/
  @ApiModelProperty(value = "Stock Type of Goods Movement (Stock Identifier)")
  public String getInventoryStockType() {
    return inventoryStockType;
  }

  public void setInventoryStockType(String inventoryStockType) {
    this.inventoryStockType = inventoryStockType;
  }

  public APIMATERIALSTOCKSRVAMatlStkInAcctModType plant(String plant) {
    this.plant = plant;
    return this;
  }

   /**
   * Plant
   * @return plant
  **/
  @ApiModelProperty(value = "Plant")
  public String getPlant() {
    return plant;
  }

  public void setPlant(String plant) {
    this.plant = plant;
  }

  public APIMATERIALSTOCKSRVAMatlStkInAcctModType storageLocation(String storageLocation) {
    this.storageLocation = storageLocation;
    return this;
  }

   /**
   * Storage Location
   * @return storageLocation
  **/
  @ApiModelProperty(value = "Storage Location")
  public String getStorageLocation() {
    return storageLocation;
  }

  public void setStorageLocation(String storageLocation) {
    this.storageLocation = storageLocation;
  }

  public APIMATERIALSTOCKSRVAMatlStkInAcctModType batch(String batch) {
    this.batch = batch;
    return this;
  }

   /**
   * Batch Number (Stock Identifier)
   * @return batch
  **/
  @ApiModelProperty(value = "Batch Number (Stock Identifier)")
  public String getBatch() {
    return batch;
  }

  public void setBatch(String batch) {
    this.batch = batch;
  }

  public APIMATERIALSTOCKSRVAMatlStkInAcctModType supplier(String supplier) {
    this.supplier = supplier;
    return this;
  }

   /**
   * Account Number of Supplier or Creditor (Stock Identifier)
   * @return supplier
  **/
  @ApiModelProperty(value = "Account Number of Supplier or Creditor (Stock Identifier)")
  public String getSupplier() {
    return supplier;
  }

  public void setSupplier(String supplier) {
    this.supplier = supplier;
  }

  public APIMATERIALSTOCKSRVAMatlStkInAcctModType customer(String customer) {
    this.customer = customer;
    return this;
  }

   /**
   * Customer Number (Stock Identifier)
   * @return customer
  **/
  @ApiModelProperty(value = "Customer Number (Stock Identifier)")
  public String getCustomer() {
    return customer;
  }

  public void setCustomer(String customer) {
    this.customer = customer;
  }

  public APIMATERIALSTOCKSRVAMatlStkInAcctModType wbSElementInternalID(String wbSElementInternalID) {
    this.wbSElementInternalID = wbSElementInternalID;
    return this;
  }

   /**
   * Valuated Sales Order Stock WBS Element
   * @return wbSElementInternalID
  **/
  @ApiModelProperty(value = "Valuated Sales Order Stock WBS Element")
  public String getWbSElementInternalID() {
    return wbSElementInternalID;
  }

  public void setWbSElementInternalID(String wbSElementInternalID) {
    this.wbSElementInternalID = wbSElementInternalID;
  }

  public APIMATERIALSTOCKSRVAMatlStkInAcctModType sdDocument(String sdDocument) {
    this.sdDocument = sdDocument;
    return this;
  }

   /**
   * Sales Order Number of Valuated Sales Order Stock
   * @return sdDocument
  **/
  @ApiModelProperty(value = "Sales Order Number of Valuated Sales Order Stock")
  public String getSdDocument() {
    return sdDocument;
  }

  public void setSdDocument(String sdDocument) {
    this.sdDocument = sdDocument;
  }

  public APIMATERIALSTOCKSRVAMatlStkInAcctModType sdDocumentItem(String sdDocumentItem) {
    this.sdDocumentItem = sdDocumentItem;
    return this;
  }

   /**
   * Sales Order Item of Valuated Sales Order Stock
   * @return sdDocumentItem
  **/
  @ApiModelProperty(value = "Sales Order Item of Valuated Sales Order Stock")
  public String getSdDocumentItem() {
    return sdDocumentItem;
  }

  public void setSdDocumentItem(String sdDocumentItem) {
    this.sdDocumentItem = sdDocumentItem;
  }

  public APIMATERIALSTOCKSRVAMatlStkInAcctModType toMaterialStock(APIMATERIALSTOCKSRVAMaterialStockType toMaterialStock) {
    this.toMaterialStock = toMaterialStock;
    return this;
  }

   /**
   * Get toMaterialStock
   * @return toMaterialStock
  **/
  @ApiModelProperty(value = "")
  public APIMATERIALSTOCKSRVAMaterialStockType getToMaterialStock() {
    return toMaterialStock;
  }

  public void setToMaterialStock(APIMATERIALSTOCKSRVAMaterialStockType toMaterialStock) {
    this.toMaterialStock = toMaterialStock;
  }

  
  
  public String getMatlWrhsStkQtyInMatlBaseUnit() {
	return matlWrhsStkQtyInMatlBaseUnit;
	}
	
	public void setMatlWrhsStkQtyInMatlBaseUnit(String matlWrhsStkQtyInMatlBaseUnit) {
		this.matlWrhsStkQtyInMatlBaseUnit = matlWrhsStkQtyInMatlBaseUnit;
	}
	
	public String getMaterialBaseUnit() {
		return materialBaseUnit;
	}
	
	public void setMaterialBaseUnit(String materialBaseUnit) {
		this.materialBaseUnit = materialBaseUnit;
	}

@Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    APIMATERIALSTOCKSRVAMatlStkInAcctModType apIMATERIALSTOCKSRVAMatlStkInAcctModType = (APIMATERIALSTOCKSRVAMatlStkInAcctModType) o;
    return Objects.equals(this.material, apIMATERIALSTOCKSRVAMatlStkInAcctModType.material) &&
        Objects.equals(this.inventorySpecialStockType, apIMATERIALSTOCKSRVAMatlStkInAcctModType.inventorySpecialStockType) &&
        Objects.equals(this.inventoryStockType, apIMATERIALSTOCKSRVAMatlStkInAcctModType.inventoryStockType) &&
        Objects.equals(this.plant, apIMATERIALSTOCKSRVAMatlStkInAcctModType.plant) &&
        Objects.equals(this.storageLocation, apIMATERIALSTOCKSRVAMatlStkInAcctModType.storageLocation) &&
        Objects.equals(this.batch, apIMATERIALSTOCKSRVAMatlStkInAcctModType.batch) &&
        Objects.equals(this.supplier, apIMATERIALSTOCKSRVAMatlStkInAcctModType.supplier) &&
        Objects.equals(this.customer, apIMATERIALSTOCKSRVAMatlStkInAcctModType.customer) &&
        Objects.equals(this.wbSElementInternalID, apIMATERIALSTOCKSRVAMatlStkInAcctModType.wbSElementInternalID) &&
        Objects.equals(this.sdDocument, apIMATERIALSTOCKSRVAMatlStkInAcctModType.sdDocument) &&
        Objects.equals(this.sdDocumentItem, apIMATERIALSTOCKSRVAMatlStkInAcctModType.sdDocumentItem) &&
        Objects.equals(this.toMaterialStock, apIMATERIALSTOCKSRVAMatlStkInAcctModType.toMaterialStock);
  }

  @Override
  public int hashCode() {
    return Objects.hash(material, inventorySpecialStockType, inventoryStockType, plant, storageLocation, batch, supplier, customer, wbSElementInternalID, sdDocument, sdDocumentItem, toMaterialStock);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class APIMATERIALSTOCKSRVAMatlStkInAcctModType {\n");
    
    sb.append("    material: ").append(toIndentedString(material)).append("\n");
    sb.append("    inventorySpecialStockType: ").append(toIndentedString(inventorySpecialStockType)).append("\n");
    sb.append("    inventoryStockType: ").append(toIndentedString(inventoryStockType)).append("\n");
    sb.append("    plant: ").append(toIndentedString(plant)).append("\n");
    sb.append("    storageLocation: ").append(toIndentedString(storageLocation)).append("\n");
    sb.append("    batch: ").append(toIndentedString(batch)).append("\n");
    sb.append("    supplier: ").append(toIndentedString(supplier)).append("\n");
    sb.append("    customer: ").append(toIndentedString(customer)).append("\n");
    sb.append("    wbSElementInternalID: ").append(toIndentedString(wbSElementInternalID)).append("\n");
    sb.append("    sdDocument: ").append(toIndentedString(sdDocument)).append("\n");
    sb.append("    sdDocumentItem: ").append(toIndentedString(sdDocumentItem)).append("\n");
    sb.append("    matlWrhsStkQtyInMatlBaseUnit: ").append(toIndentedString(matlWrhsStkQtyInMatlBaseUnit)).append("\n");
    sb.append("    materialBaseUnit: ").append(toIndentedString(materialBaseUnit)).append("\n");
    sb.append("    toMaterialStock: ").append(toIndentedString(toMaterialStock)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

