/*
 * Material Stock Display
 * This service enables you to retrieve material stock information using the OData protocol with filter data provided in the payload. It can be consumed by external warehouse applications.
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.sap.apibhub.sdk.api_material_stock_srv.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.sap.apibhub.sdk.api_material_stock_srv.model.OdataErrorDetail;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * OdataErrorMain
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-08-07T13:00:53.757Z")
public class OdataErrorMain {
  @SerializedName("code")
  private String code = null;

  @SerializedName("message")
  private String message = null;

  @SerializedName("target")
  private String target = null;

  @SerializedName("details")
  private List<OdataErrorDetail> details = null;

  @SerializedName("innererror")
  private Object innererror = null;

  public OdataErrorMain code(String code) {
    this.code = code;
    return this;
  }

   /**
   * Get code
   * @return code
  **/
  @ApiModelProperty(required = true, value = "")
  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }

  public OdataErrorMain message(String message) {
    this.message = message;
    return this;
  }

   /**
   * Get message
   * @return message
  **/
  @ApiModelProperty(required = true, value = "")
  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }

  public OdataErrorMain target(String target) {
    this.target = target;
    return this;
  }

   /**
   * Get target
   * @return target
  **/
  @ApiModelProperty(value = "")
  public String getTarget() {
    return target;
  }

  public void setTarget(String target) {
    this.target = target;
  }

  public OdataErrorMain details(List<OdataErrorDetail> details) {
    this.details = details;
    return this;
  }

  public OdataErrorMain addDetailsItem(OdataErrorDetail detailsItem) {
    if (this.details == null) {
      this.details = new ArrayList<OdataErrorDetail>();
    }
    this.details.add(detailsItem);
    return this;
  }

   /**
   * Get details
   * @return details
  **/
  @ApiModelProperty(value = "")
  public List<OdataErrorDetail> getDetails() {
    return details;
  }

  public void setDetails(List<OdataErrorDetail> details) {
    this.details = details;
  }

  public OdataErrorMain innererror(Object innererror) {
    this.innererror = innererror;
    return this;
  }

   /**
   * The structure of this object is service-specific
   * @return innererror
  **/
  @ApiModelProperty(value = "The structure of this object is service-specific")
  public Object getInnererror() {
    return innererror;
  }

  public void setInnererror(Object innererror) {
    this.innererror = innererror;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OdataErrorMain odataErrorMain = (OdataErrorMain) o;
    return Objects.equals(this.code, odataErrorMain.code) &&
        Objects.equals(this.message, odataErrorMain.message) &&
        Objects.equals(this.target, odataErrorMain.target) &&
        Objects.equals(this.details, odataErrorMain.details) &&
        Objects.equals(this.innererror, odataErrorMain.innererror);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, message, target, details, innererror);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OdataErrorMain {\n");
    
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    target: ").append(toIndentedString(target)).append("\n");
    sb.append("    details: ").append(toIndentedString(details)).append("\n");
    sb.append("    innererror: ").append(toIndentedString(innererror)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

