package com.sap.xi.sd_sls;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * 
 * 		
 *
 * This class was generated by Apache CXF 3.2.6
 * 2018-11-21T10:16:43.701+05:30
 * Generated source version: 3.2.6
 *
 */
@WebService(targetNamespace = "http://sap.com/xi/SD-SLS", name = "SalesOrderBulkRequest_In")
@XmlSeeAlso({com.sap.xi.sapglobal20.global.ObjectFactory.class, ObjectFactory.class, com.sap.xi.sd.ObjectFactory.class, com.sap.xi.sd.global2.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SalesOrderBulkRequestIn {

    @WebMethod(operationName = "SalesOrderBulkRequest_In", action = "http://sap.com/xi/SD-SLS/SalesOrderBulkRequest_In/SalesOrderBulkRequest_InRequest")
    @Oneway
    public void salesOrderBulkRequestIn(
        @WebParam(partName = "SalesOrderBulkRequest", name = "SalesOrderBulkRequest", targetNamespace = "http://sap.com/xi/SD-SLS")
        SalesOrderBulkMessage salesOrderBulkRequest
    );
}
