
package com.sap.xi.sd_sls;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2018-11-21T10:15:02.438+05:30
 * Generated source version: 3.2.6
 *
 */

public class SalesOrderBulkRequestIn_BindingSoap12_Server{

    protected SalesOrderBulkRequestIn_BindingSoap12_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new Binding_Soap12Impl();
        String address = "https://my301713-api.s4hana.ondemand.com/sap/bc/srt/scs/sap/salesorderbulkrequest_in?sap-client=100";
        Endpoint.publish(address, implementor);
    }

    public static void main(String args[]) throws java.lang.Exception {
        new SalesOrderBulkRequestIn_BindingSoap12_Server();
        System.out.println("Server ready...");

        Thread.sleep(5 * 60 * 1000);
        System.out.println("Server exiting");
        System.exit(0);
    }
}
