package com;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2019-07-30T15:34:59.929+05:30
 * Generated source version: 3.2.6
 *
 */
@WebService(targetNamespace = "http://com/", name = "Z_B2B_CUST_INQ")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ZB2BCUSTINQ {

    @WebMethod
    @WebResult(name = "getCustomerValidationResponse", targetNamespace = "http://com/", partName = "getCustomerValidationResponse")
    public Zb2BCustInqWrapper getCustomerValidation(
        @WebParam(partName = "customerId", name = "customerId", targetNamespace = "http://com/")
        java.lang.String customerId
    ) throws Exception_Exception;
}
